baseurl      = "blog.korbexmachina.com"
title        = "Korben Tompkin"
subtitle = "A simple theme for Hugo"
keywords = ""
readOtherPosts = "Read other posts"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10


[author]
name = "Korben Tompkin"

[params]
dateform        = "Jan 2, 2006"
dateformShort   = "Jan 2"
dateformNum     = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
homeSubtitle = "My technical blog."

# Set disableReadOtherPosts to true in order to hide the links to other posts.
disableReadOtherPosts = false

# Enable sharing buttons, if you like
enableSharingButtons = true

# Show a global language switcher in the navigation bar
enableGlobalLanguageMenu = false

# Metadata mostly used in document's head
description = "My new homepage or blog"
keywords = "homepage, blog"
images = [""]

# Social icons
[[params.social]]
name = "github"
url  = "https://github.com/korbexmachina"

[[params.social]]
name = "email"
url  = "mailto:contact@korbexmachina.com"

[[params.social]]
name = "mastodon"
url  = "https://mstdn.social/@korbexmachina"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/korbentompkin/"

[[params.social]]
name = "pixelfed"
url  = "https://pixelfed.social/i/web/profile/577945488650438877"

[[params.social]]
name = "keybase"
url  = "https://keybase.io/korbexmachina"

[taxonomies]
category = "blog"
tag      = "tags"
series   = "series"

[params.logo]
logoText = "Home"
logoHomeLink = "/"
logoMark     = " "
logoCursorDisabled = true
# logoCursorAnimate  = "0s"
# logoCursorColor    = "#ffffff"
# or
#
# path = "/img/your-example-logo.svg"
# alt = "Your example logo alt text"
[params.footer]
trademark = true
rss = true
author = true

topText = []
bottomText = [
  "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
]

# And you can even create generic menu
[menu]
[[menu.main]]
identifier = "blog"
name       = "Blog"
url        = "/posts"

[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about"

[[menu.main]]
identifier = "disclaimer"
name       = "Disclaimer"
url        = "/disclaimer"
